name: smalltalkCI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [ Pharo64-11 Pharo64-10, Pharo64-9.0, GemStone64-3.6.6, GemStone64-3.5.4 ]
        experimental: [ false ]
        include:
          - smalltalk: Pharo64-alpha
            experimental: true
    continue-on-error: ${{ matrix.experimental }}
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v3
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Run tests
        run: smalltalkci -s ${{ matrix.smalltalk }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash